### ISSUE TITLE
San Diego Anesthesiologist group Antibody testing data

### ISSUE THREAD

**Issue by drgoodwrench** [outbreak-info/outbreak.info#100]
ASMG, a 250+ member anesthesiology group in San Diego made Antibody testing available to all members this week. Is there a place for the results data to be used?
Dr. John Reed

**Comment by gkarthik** [comment]
@drgoodwrench this is definitely something that can be incorporated. A couple of quick questions,

1. How many tests have been conducted? 
2. What is the format of the data? Specifically, is this +ve and -ve or do you incorporate additional data such as location for example. 
3. Is it currently accessible online? 

Thanks!

**Comment by drgoodwrench** [comment]
I am just one of the anesthesia providers, and not a programmer in any form...vcr still has me stumped...but..
Let me know how you want the data and i will try and get it supplied in this format. I will find out how many were tested, how many were positive, either IgM or IgG or both, and can say all practiced in San Diego county. I might be able to get responses from those tested if specific questions need to be asked, Best to email me direct as I may not find my way back to this site!
John Reed
drgoodwrench@gmail.com
