### ISSUE TITLE
Add subnational population data to enable front-end calculation of per capita numbers

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#126]

**Comment by flaneuse** [comment]
U.S. county-level data: https://www.census.gov/data/tables/time-series/demo/popest/2010s-counties-total.html

**Comment by gkarthik** [comment]
@malkuzweny relevant issue. Let's start with the US and add population count to US admin1, county and metro area shape files. We can then easily add population attribute while preprocessing data.

**Comment by flaneuse** [comment]
Can also loop in @juliamullen if you need help, especially with incorporating it into the python code
