### ISSUE TITLE
Ensure /metadata date updated reflects Daylight Savings Time

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#154]
With the server time being converted to PDT from UTC, the time parsing of the `build_date` in https://api.outbreak.info/covid19/metadata will shift during Daylight Savings Time.  Ensure the date updated is accurate.

**Comment by gkarthik** [comment]
Hacky solution (or as @flaneuse rightly put it, 🤮): Check [worldclockapi](http://worldclockapi.com/api/json/pst/now) for PST if `isDayLightSavingsTime ==true` then parse as -7 else -8.

**Comment by flaneuse** [comment]
Closed with https://github.com/outbreak-info/outbreak.info/compare/c06038b6ffe2...cc2cefe0a0ca
