### ISSUE TITLE
GENOMICS API: Return 0s for lineage-by-country-most-recent

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#191]
When pulling the countries that have detected a given lineage (e.g. B2), we should also pull the countries that have done sequencing but haven't found the strain yet (the 0 vs. NA issue).  

e.g. --

http://kenny.scripps.edu:8888/api/lineage-by-country-most-recent?pangolin_lineage=B.2

should be UK + ~140 other countries with 0 values.

**Comment by gkarthik** [comment]
Closed in https://github.com/outbreak-info/outbreak.api/commit/c49343568cf7fa4d767854f1f28d77e605723cbe
