### ISSUE TITLE
GENOMICS API: add filter parameter to most recent collection date by lineage

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#193]
convert http://kenny.scripps.edu:8888/api/most-recent-collection-date

to http://kenny.scripps.edu:8888/api/most-recent-collection-date?pangolin_lineage=P.1

so you can also return only the P.1 object:

```
{
"lineage": "P.1",
"date": "2021-01-12",
"date_count": 1,
"total_count": 31
}
```

**Comment by flaneuse** [comment]
note for @gkarthik : fine for now, I can filter it on the front-end.

**Comment by gkarthik** [comment]
Closing before merge into master to keep track
