### ISSUE TITLE
GENOMICS API: Add rolling average or other smoothing to all lineages prevalence

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#194]
In http://kenny.scripps.edu:8888/api/prevalence-by-country-all-lineages?country=United%20Kingdom
-- calculate prevalence by day, smoothed.

I don't think there's a need to also calculate confidence intervals, since it'd get too gummy to visualize.

I will also lump all low-prevalence strains into an "other" category, but that can happen on the front-end at least initially.

**Comment by gkarthik** [comment]
Closed in https://github.com/outbreak-info/outbreak.api/commit/627d5210b37b0f475fc96d493749710ade18e882.
