### ISSUE TITLE
GENOMICS API: add nesting mapping for `mutations`

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#201]
Add nested mapping type for `mutations` so we can leverage ES to get a set of mutations. Right now its a temporary fix that uses the mutation name,"S:N501Y" to get pos, alt_aa, ref_aa etc

**Comment by juliamullen** [comment]
https://github.com/juliamullen/genomics_parser/commit/d8e685724272d2d82f247249fb0c2a16914d5eb3
