### ISSUE TITLE
Situation Reports: reroute from old URLs

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#214]
e.g. https://outbreak.info/situation-report/B-1-1-7 to https://outbreak.info/situation-report?pangolin=B.1.1.7

**Comment by andrewsu** [comment]
FWIW, I think using `pangolin` as the URL parameter is confusing.  I understand (now) that the name of the tool used to generate the lineages is "pangolin". But given the history that the pangolin (the animal) was at one point thought to be an intermediary host, it did confuse me (I'm not looking at virus sequences isolated from animals, am I?)  

For me, I think `lineage` would be a better parameter name.  Minimally, I would repeat add the link to [Pangolin lineages](https://cov-lineages.org/lineages.html) to the footer of every situation report page (not just the index page).  That at least would have helped me when my first instinct was to control-F to try to find why pangolins were relevant...

**Comment by flaneuse** [comment]
@andrewsu This was intentional in case we want to expand to using nextstrain strains (lineages) as a parameter. (Eg situation-report?nextstain=xyz)

@gkarthik @AlaaALatif that's still on the agenda, right?

Will add a link to pangolin on the report though-- that's a good idea.

**Comment by andrewsu** [comment]
do the lineage names clash between pangolin and nextstrain?  If not, you could use `lineage` and figure it out on the back end.  and that solution also has the benefit of saving you the trouble of figuring out error handling for `situation-report?pangolin=B.1.1.7&nextstrain=xyz`.  

And not to belabor the point, but I will say the whole pangolin thing was disorienting/confusing enough to me that -- were I a completely naive third-party user -- I might have filed this under "I'm not getting something fundamental here so I'm going to come back to this later."  The cognitive dissonance seeing an animal next to a strain name was quite jarring...

**Comment by andrewsu** [comment]
... and as another alternative, https://cov-lineages.org/lineages.html refers to "PANGO lineages", so even `pango` as a parameter name would be better IMO...

**Comment by gkarthik** [comment]
"PANGO lineages" is indeed the official name. We were using the field names in the data dump we were getting and hence, `pangolin_lineage`. The reason we decided to separate out the parameters into `pangolin` and `nextclade` (in future versions) is to avoid the trouble of figuring this out on the backend. On error handling, I need to think about this more. 

Regarding the use of the word "Pangolin" itself, I see your point. I think we should explore the possibility of just showing the lineage name and redirecting to `https://cov-lineages.org/lineages/lineage_B.1.1.7.html`.

**Comment by flaneuse** [comment]
Will switch to PANGO for the labels instead of Pangolin, yes.  That's their official name but it seems like people (or at least we) have been referring to it as "pangolin" because it's cute.  I'll also add a link to the strain-specific PANGO page; I'd planned on doing so but slipped off my radar.

I like the idea of switching to `?lineage` to cover both nextstrain clades and PANGO lineages; it's cleaner and the url already gets obnoxiously long w/ the location specifications.  The two arguments that I see against it are:

1. If we ever wanted to specify both a PANGO lineage and a Nextstrain clade.  That use case does exist for a custom list of mutations -- e.g.  -- BUT in this case, I can't see that making much sense to select Nextstrain and PANGO simultaneously.
2. If it's too complicated on the backend to be able to sort out "20J/501Y.V3" --> Nexstrain and P.1 --> PANGO.  Seems like there'd just be a pre-filter to the existing queries to lookup whether it's a valid Nextstrain or PANGO lineage and then route through the existing architecture.  But I'm not writing it, so I'm not sure about the actual difficulty or the performance hit for doing that lookup.

@gkarthik I'd like to get this resolved before we launch since it changes all the routes, so can you make the call?
