### ISSUE TITLE
GENOMICS API: Expand all endpoints to allow a series of mutations

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#238]
Instead of `pangolin_lineage`, specify a series of mutations to calculate prevalence/counts, etc.

**Comment by gkarthik** [comment]
The following endpoints now accept lineage and/or a set of mutations.

genomics/lineage-by-country
genomics/lineage-by-division
genomics/lineage-and-country
genomics/lineage-by-division-most-recent
genomics/lineage-by-country-most-recent
genomics/prevalence-by-location
genomics/prevalence-by-location
genomics/global-prevalence
genomics/most-recent-submission-date
genomics/most-recent-collection-date
genomics/mutations

Closing so we can open issues to add more endpoints or track bugs on individual endpoints.
