### ISSUE TITLE
GENOMIC DATA: Make sure Admin 0 / country names are normalized to Natural Earth names

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#242]
Natural Earth names:
https://github.com/outbreak-info/outbreak.info/blob/master/web/src/assets/geo/countries.json

Related to #236 but for countries.  Countries will use Natural Earth boundaries and Divisions GADM (I think?) since they match better to the names already in GISAID.

**Comment by flaneuse** [comment]
Known issues:

Dominican Republic != Dominican Rep.

**Comment by AlaaALatif** [comment]
Location normalization should now capture all country-level information submitted to GISAID except for the following:
{'Caribbean', 'Crimea'}

These were not normalized to a GADM country name. In total, this accounts for 19 samples submitted to GISAID as of 2021-02-16. 

An updated notebook with location normalization can be found [here](https://github.com/andersen-lab/bjorn/blob/master/notebooks/gisaid_feed_processing.ipynb)

Going to close this after complete deployment and sanity checks
