### ISSUE TITLE
Situation report: weird URL routing

### ISSUE THREAD

**Issue by andrewsu** [outbreak-info/outbreak.info#243]
If I start at https://outbreak.info/situation-reports-demo and click on B.1.1.7, I go to https://outbreak.info/situation-report-demo?pangolin=B.1.1.7 -- note difference between `reports` and `report` in the URL.  Then, if I'm lazy and want to trim the URL to https://outbreak.info/situation-report-demo, I essentially get to a blank page. 

I think better behavior would be to stick to either `reports` or `report`, or at least redirect https://outbreak.info/situation-report-demo to https://outbreak.info/situation-reports-demo

**Comment by gkarthik** [comment]
We'll keep this in mind but I think should be corrected when we move to just `/situation-reports/`.
