### ISSUE TITLE
Normalize Admin2 location names to match geographic areas in the United States (U.S. counties)

### ISSUE THREAD

**Issue by AlaaALatif** [outbreak-info/outbreak.info#266]
This would allow us to represent SARS-CoV-2 mutation/variant prevalence down to the county-level inside the United States.

**Comment by AlaaALatif** [comment]
Location normalization should now capture all U.S. county-level information submitted to GISAID, except for the following:

{'', 'Gulf Coast', 'HA', 'M', 'Mclennan', 'Nan', 'Napa Solano Yolo Marin Counties', 'None', 'Out Of State', 'Out of state', 'Out-Of-State', 'Out-of-state', 'Ponce', 'South West', 'Southeast', 'Southwest', 'UNKNO', 'Unknown', 'Western Alaska', 'unknown'}

In total (as of 2021-02-16), this accounts for 183 samples submitted to GISAID from the U.S. where a value was entered in the relevant field and has not been normalized to GADM nomenclature (Admin2). 

An updated notebook with location normalization can be found [here](https://github.com/andersen-lab/bjorn/blob/master/notebooks/gisaid_feed_processing.ipynb)

Going to close this after complete deployment and sanity checks.

**Comment by flaneuse** [comment]
@AlaaALatif i would convert the unknown/unk etc to None.

**Comment by flaneuse** [comment]
Closing aside from specific issues like #308
