### ISSUE TITLE
Situation report: case normalize mutations to send to the backend

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#278]
Fix if a user types s:n501y, for instance.

**Comment by flaneuse** [comment]
Temp fix ignored the fact that ORF1a needs to be "1a" not "1A", so we can't just force everything to be uppercased.

Need to keyword-normalize on the backend.

**Comment by flaneuse** [comment]
@gkarthik will there be any downstream effects on the endpoints?

I won't need to pass you lowercased values, right?

**Comment by gkarthik** [comment]
I can handle converting to lowercase on the API. So, I don't expect a problem with that bit.

**Comment by flaneuse** [comment]
Closed with #305
