### ISSUE TITLE
Issues with mutation tables 

### ISSUE THREAD

**Issue by kea027** [outbreak-info/outbreak.info#279]
1. https://outbreak.info/situation-reports?pango=P.1
C174G should be G174C as the reference codon is GGC

2. https://outbreak.info/situation-reports?pango=B.1.429
5UTR mutation C241T should not be translated (listed as R81C)

**Comment by AlaaALatif** [comment]
Hey, thank you for letting us know about this. 

Yes, you're correct. I checked our upstream mutation database and confirmed that the mutation observed is G174C; **not** C174G (please find link to screenshot showing details below).

This looks like it might be a downstream issue and we are still trying to identify it. Will keep you posted.

**Comment by flaneuse** [comment]
Thanks so much @kea027 for bringing this to our attention.

For the curated reports, we are using the characteristic mutations from the [CDC](https://www.cdc.gov/mmwr/volumes/70/wr/mm7003e2.htm), which has the C and G switched.  All the other data on the page is pulling from the GISAID data. We've fixed the data on our side so the list of mutations is correct.

We're working on removing all 5'UTR and 3'UTR mutations from displaying.

Thanks again, and please let us know if you come across other issues or have feature requests!

**Comment by kea027** [comment]
No problem, happy to help.  One feature that would be useful is to have the nucelotide changes in addition to the amino acid changes listed in the mutation tables.

**Comment by flaneuse** [comment]
Definitely a great idea, will add it to the list of things to do.
