### ISSUE TITLE
Collapse out-of-state, None options for counties

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#294]
E.g. New York counties:
Many out-of-state variations
<img width="384" alt="Screen Shot 2021-03-09 at 12 50 31 PM" src="https://user-images.githubusercontent.com/8041065/110522192-43930f80-80d6-11eb-879f-2b086daa3358.png">

Plus some `None` locations

https://dev.outbreak.info/genomics/lineage-by-sub-admin-most-recent?location_id=USA_US-NY&pangolin_lineage=B.1.526&timestamp=448699

**Comment by gkarthik** [comment]
Fixed in https://github.com/outbreak-info/outbreak.api/commit/68d3d9abfae5e06531d822bdee8bac8378b3caf8. 
Collapsed variations of "out of state" into Out of state.
Collapsed "None" and variations of unknown into "Unknown" to show those sequences without sub admin information.
