### ISSUE TITLE
Filter "None" as an option for county-level data

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#301]
There are a lot of locations which are:

country: X
division: Y
county: None

I don't think we want these to be selectable as a location, since `None, England, UK` doesn't make a ton of sense.  I think we want to force people to look at the divisional data, right?  (e.g. all `England, UK`)

<img width="510" alt="Screen Shot 2021-03-13 at 12 27 47 PM" src="https://user-images.githubusercontent.com/8041065/111040231-97179d00-83f7-11eb-8425-5ba5f4399d5b.png">

**Comment by gkarthik** [comment]
Fixed in https://github.com/outbreak-info/outbreak.api/commit/c6591b307e8911502f2f23848ab638b79412766e
