### ISSUE TITLE
Incorrect UI behavior when trying to view B.1.1.7 data for Puerto Rico

### ISSUE THREAD

**Issue by sacundim** [outbreak-info/outbreak.info#308]
When I visit the variant tracker for B.1.1.7 and I try to view data for Puerto Rico, the application behaves in a way that's clearly incorrect. I click on the "change locations" link, type in "Puerto Rico," and the autocomplete so far shows me this that doesn't look obviously wrong:

<img width="553" alt="Screen Shot 2021-03-16 at 5 35 36 PM" src="https://user-images.githubusercontent.com/4076056/111399509-c2fa8300-8682-11eb-8d82-e23d056fe0bd.png">

Then I select it from the autocomplete, and it still looks right:

<img width="544" alt="Screen Shot 2021-03-16 at 5 35 49 PM" src="https://user-images.githubusercontent.com/4076056/111399550-d60d5300-8682-11eb-90cd-b4c2f855a4c0.png">

But when I click on "save changes," the page is updated to add "Houston, United States": 

<img width="471" alt="Screen Shot 2021-03-16 at 5 36 54 PM" src="https://user-images.githubusercontent.com/4076056/111399658-06ed8800-8683-11eb-840c-3033c2839923.png">

Which doesn't seem to be the data for the actual city of Houston, Texas, United States, that's another entry:

<img width="470" alt="Screen Shot 2021-03-16 at 5 40 46 PM" src="https://user-images.githubusercontent.com/4076056/111399697-1a98ee80-8683-11eb-9527-080df6b06cda.png">

The URL query string parameter for this suspicious "Houston, United States" is `USA_US-None`, which is very suspicious:

* https://outbreak.info/situation-reports?pango=B.1.1.7&loc=USA_US-None&selected=USA_US-None

When I go further down in the page to look at the time series chart, four of the earlier cases I see match up with the dates of B.1.1.7 sequences I knew about in Puerto Rico independently (Jan 22, Jan 27, Feb 1, Feb 18), but I don't have an independent source on the others, so I can't tell whether the other ones are correct:

<img width="770" alt="Screen Shot 2021-03-16 at 6 14 32 PM" src="https://user-images.githubusercontent.com/4076056/111400028-b9254f80-8683-11eb-9c2b-ad2c46c37327.png">

**Comment by gkarthik** [comment]
Thank you for pointing this out. We recently changed how we handled locations internally and this seems to be an artifact of those changes. As you correctly inferred, what you are seeing is not the data for Puerto Rico. We will work on a fix for this.

**Comment by flaneuse** [comment]
Thanks for the very detailed bug report @sacundim!  This is very helpful to debug this problem.

@AlaaALatif @gkarthik -- within Bjorn can we run a check on all `location_ids` to ensure that:
1. they're unique (pretty sure we're missing edge cases atm.
2. they don't contain "None" anywhere in them?

**Comment by gkarthik** [comment]
Yes, that was my first thought but that would exclude any location with `None` in the id. A potential long term solution would be to capture these exceptions (probably in an ad-hoc manner) and assign ids to them.

**Comment by sacundim** [comment]
I just went to check whether this issue is still ongoing and it still is.  I also tried the Location Tracker and found the same issue. Steps to reproduce:

1. Go to https://outbreak.info/location-reports
2. Type "Puerto Rico" into the "Select location" box
3. It's not offered as a completion option

<img width="1304" alt="Screen Shot 2021-04-30 at 6 00 36 PM" src="https://user-images.githubusercontent.com/4076056/116766177-ff3d3500-a9dd-11eb-8aef-4a721f502423.png">

In contrast, Guam and the Northern Mariana Islands do appear in the UI (but not the USVI): 

* https://outbreak.info/location-reports?loc=GUM
* https://outbreak.info/location-reports?loc=MNP

I tried URL-hacking and none of these works:

* https://outbreak.info/location-reports?loc=USA_US-PR
* https://outbreak.info/location-reports?loc=PUR

**Comment by gkarthik** [comment]
Hello @sacundim , unfortunately we haven't fixed this issue yet. We have a few more things in the pipeline to get through but we will be looking into geographic normalization over the next few weeks. We will keep you posted! Thank you for raising this issue once again!

**Comment by sacundim** [comment]
I just managed to search for the location report for Puerto Rico on the page, and click through to it.

* https://outbreak.info/location-reports?loc=PRI

**Comment by gkarthik** [comment]
We fixed this issue during an ongoing series of fixes for specific locations. Thank you for pointing this out! Closing this now.
