### ISSUE TITLE
Mutation Reports: Location "Usa" providing data for Bonaire

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#328]
From Lineage/Mutation reports or Location reports, a location comes up called "Usa" (171 total sequences as of 4/5/21) and selecting it provides data for Bonaire.

**Comment by flaneuse** [comment]
@AlaaALatif Please fix in the Bjorn pipeline.  Thanks!

**Comment by gkarthik** [comment]
All these sequences should be "USA". Please check for lowercase while getting the country ids.

**Comment by AlaaALatif** [comment]
@flaneuse what is the field name that gets used for the search query that brings up "Usa"? Is it `country_id`, `country`, or `country_original`?

**Comment by flaneuse** [comment]
Country I believe.

**Comment by AlaaALatif** [comment]
Potential fix in 52a4ffe4f4dafc62589445007786c854093c67e5
Will confirm after upcoming data update in <2hrs

**Comment by AlaaALatif** [comment]
Fix appears to solve the issue. Checked both the upstream data and the search query bar for the location reports in production. 

Closing for now, please feel free to reopen otherwise.
