### ISSUE TITLE
Site is mismatching umlauted chars (e.g. åäö) compared to gisaid

### ISSUE THREAD

**Issue by LordRust** [outbreak-info/outbreak.info#334]
GISAID does not allow any special chars, so e.g. in Sweden we do have several regions with [åäö] in them, like Skåne.

GISAID forces us to submit as "skane", but in the geographic searches and matching outbreak.info uses the umlauted "skåne". Resulting in that nothing can be matched to that region

As an example [B.1.1.7 for all of Sweden](https://outbreak.info/situation-reports?pango=B.1.1.7&selected=SWE&loc=SWE) where one can note that all regions with åäö are missing data.

**Comment by flaneuse** [comment]
Thanks @LordRust, we'll work on fixing this.

@gkarthik: Can you see why Skane/Skåne isn't available in the location lookup?

**Comment by AlaaALatif** [comment]
Hello, thanks @LordRust for the feedback. We just pushed an update that should fix the issue for the following regions in Sweden:

- Södermanland
- Gävleborg
- Jämtland
- Jönköping
- Östergötland
- Skåne
- Södermanland
- Värmland
- Västerbotten
- Västernorrland
- Västmanland
- Västra Götaland

Changes should hopefully be reflected on the website later today.

**Comment by AlaaALatif** [comment]
https://outbreak.info/location-reports?loc=SWE
