### ISSUE TITLE
Erroneously no data for Sachsen-Anhalt displayed, despite presence on GISAID

### ISSUE THREAD

**Issue by corneliusroemer** [outbreak-info/outbreak.info#344]
I love this website, it's so good to compare the proportion of different variants in different countries and regions.

I noticed, that you display no data for the German state of Saxony-Anhalt (Sachsen-Anhalt) even though there definitely **are** sequences from Sachsen-Anhalt on GISAID, see screenshots.

Also, it looks like you're not using all German sequences. On Gisaid there seem to be more than 75k sequences. Yet on outbreak.info you only count 64813 sequences. What's the reason for this discrepancy? Are some sequences not used due to matching problems?

There's a similar issue with Tirol/Tyrol in Austria. There definitely are sequences, but you are not showing them on outbreak.ifno

No data for Sachsen-Anhalt
![image](https://user-images.githubusercontent.com/25161793/116237980-20ddb880-a761-11eb-83d3-b3bd91602362.png)

But on GISAID there clearly are sequences from Saxony-Anhalt (ST), more than 2k!
![image](https://user-images.githubusercontent.com/25161793/116238066-394dd300-a761-11eb-923b-e95fb4cb0c3e.png)

**Comment by flaneuse** [comment]
Thanks @corneliusroemer for raising this issue and glad to hear you like the site.

On the first issue, we've worked to match and normalize all the place names provided for GISAID to physical geographic locations, but there are occasionally edge cases that we miss.  @AlaaALatif can you fix the Bjorn normalization of Saxony-Anhalt?  It looks like you're converting both Saxony and Saxony-Anhalt to Sachsen; switching line [217 and 218](https://github.com/andersen-lab/bjorn/blob/95447eb216edeb83e1ddc72d6608818a71b5f81c/src/json2fasta.py#L218) should do the trick.  We'll let you know when this update is pushed.

@AlaaALatif can you look at Tirol/Tyrol (as well as the issue with accents in Sweden #334)?

On the lower sequence count versus GISAID: that's not a location name normalization issue, but rather from filters we use to remove sequences with poor quality data.  They're fully described in our [methods](https://outbreak.info/situation-reports/methods).

Please let us know if you have more questions or suggestions!

**Comment by AlaaALatif** [comment]
Thanks @corneliusroemer for the feedback. We just pushed an update to fix location issues for Saxony-Anhalt, Germany and Tirol, Austria. 
https://github.com/andersen-lab/bjorn/commit/f02d92eb8767cde484f076d8c207f5b00847f510

Changes should hopefully be reflected on the website later today.

**Comment by AlaaALatif** [comment]
Sachsen-Anhalt: https://outbreak.info/location-reports?loc=DEU_DE-ST
Tirol: https://outbreak.info/location-reports?loc=AUT_AT-TR
