### ISSUE TITLE
Question: Where is the code for the genomics API backend and documentation?

### ISSUE THREAD

**Issue by corneliusroemer** [outbreak-info/outbreak.info#345]
You've built a really great tool, thanks a lot!

I'd be interested in seeing how you pull in GISAID data and do the backend stuff. However, I couldn't find the code anywhere. Neither here nor over in the outbreak-info / api repo.

Am I blind or have you not open sourced that part yet?

Also, I couldn't find the documentation for the /genomics endpoint. I presume it doesn't exist?

Thanks a lot!

**Comment by flaneuse** [comment]
Sure, glad to help.

The data processing pipeline is all contained within the [Bjorn project](https://github.com/andersen-lab/bjorn), which is confusingly in a separate repository and not in the outbreak.info organization. The methodology is briefly described on our [methods page](https://outbreak.info/situation-reports/methods).

We're working on setting up an agreement to allow API access to the /genomics endpoint and will add documentation then.  We'll let you know when it's in place.

**Comment by corneliusroemer** [comment]
I've found some documentation already ;)
https://github.com/outbreak-info/outbreak.api/blob/master/web/handlers/genomics/docs.md
