### ISSUE TITLE
Swiss cantons are not recognised correctly

### ISSUE THREAD

**Issue by corneliusroemer** [outbreak-info/outbreak.info#348]
The issue here with Switzerland seems to be very similar to the recently solved issue #344.

There are a lot of different canton names that are not normalised correctly, causing some cantons to show 0 sequences, which is definitely not correct.

**Comment by corneliusroemer** [comment]
Swiss cantons seem to be quite some mess here, I'm happy to help out canonicalising @AlaaALatif  if you show me how.
![image](https://user-images.githubusercontent.com/25161793/116819487-8de1bb80-ab70-11eb-8942-a9625616afa1.png)

**Comment by corneliusroemer** [comment]
Ah I think I've figured it out, you're using ISO3166, so if I use a correct subdivision name it should work out.

For example Zürich will make it CHE_CH-ZH. I'll prepare a PR for Switzerland for you, let's hope it works :)

**Comment by AlaaALatif** [comment]
Reopening until the Admin1 Swiss locations are displayed as expected on outbreak.info.

**Comment by corneliusroemer** [comment]
Not yet, still waiting for the update 
[Tense](https://c.tenor.com/CUlOCFQPDBQAAAAM/kermit-kermit-the-frog.gif)

**Comment by corneliusroemer** [comment]
Is it normal that the commit has had no effect yet? When do you expect it to have an effect @AlaaALatif?
![image](https://user-images.githubusercontent.com/25161793/117054850-d4731980-ad1a-11eb-90ee-acb389faede1.png)

**Comment by corneliusroemer** [comment]
Now the normalizations took effect, there are just a few more cleanups necessary, done here: https://github.com/andersen-lab/bjorn/pull/12
