### ISSUE TITLE
Make B.1.617.2 VOI instead of B.1.617

### ISSUE THREAD

**Issue by corneliusroemer** [outbreak-info/outbreak.info#351]
B.1.617.2 is the other "Indian" variant that's growing fast. In fact, even faster than B.1.617.1

It's in some experts' eyes potentially more concerning, just look at the explosive growth.

B.1.617 however doesn't make much sense anymore as a VOI, it got split into the 3 sublineages.

So I'd recommend elevating B.1.617.2 to frontpage status and drop B.1.617

Just look at this growth worldwide:
![image](https://user-images.githubusercontent.com/25161793/117055899-fd47de80-ad1b-11eb-8092-e4f9b1c6f355.png)

https://twitter.com/chrischirp/status/1389650690683936770?s=20

**Comment by gkarthik** [comment]
A lot of B.1.617.2 cases seem to be travel related originating from India. Such travel cases might artificially inflate the prevalence despite very low levels of community transmission. Even in India, the prevalence of B.1.617.* lineages is biased by under sampling. Further, B.1.617.2 doesn't seem to have the S:E484Q mutation which is more prevalent in B.1.617, B.1.617.1, and B.1.617.3. However, we are keeping an eye out for B.1.617.* lineages but we need more data to evaluate which ones should be a VOI. 

![image](https://user-images.githubusercontent.com/798263/117056828-9bfb1d80-acd1-11eb-9d26-3652a60d436d.png)

**Comment by corneliusroemer** [comment]
Yes, I know that travel is very important. But still, even if it's all just travel, it would mean that the variant is increasing a lot at the source. It's been growing fast in both UK, USA and Singapore.

It's mostly that I think B.1.617 makes no sense anymore, and that B.1.617.2 is much more worthy of attention.

B.1.617 has just 100 sequences in total, getting fewer by the day due to pango getting updates. B.1.617.2 has 600 and counting.

**Comment by gkarthik** [comment]
Yes, we are keeping an eye out on the B.1.617.* lineages. We will update as more data comes in.

**Comment by corneliusroemer** [comment]
This issue aged well ;)
