### ISSUE TITLE
Add official WHO variant designation to variant overview

### ISSUE THREAD

**Issue by corneliusroemer** [outbreak-info/outbreak.info#366]
WHO has come up with an official naming scheme for major variants. Would probably be good to add that as an alias in addition to pango at least on some websites, like the variant overview as an a.k.a https://outbreak.info/situation-reports

https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/ 

![image](https://user-images.githubusercontent.com/25161793/120234392-25155e00-c258-11eb-8fc1-06f59e88b2b2.png)

**Comment by gkarthik** [comment]
We are documenting VOC/VOI classifications from different organizations so the table is very useful. Thanks!
