### ISSUE TITLE
It is possible to get a broken display on compare-lineages

### ISSUE THREAD

**Issue by theosanderson** [outbreak-info/outbreak.info#375]
To reproduce (on Chrome):

Go to https://outbreak.info/compare-lineages
Press `Change Lineages`
Press `+ ADD VOIs`

For me this leads to <img src="https://i.imgur.com/ePRhNbg.png">

If you instead clear and then add e.g. VOCs and VUIs everything works fine.

Sorry if this is a known issue. It's a great tool.

**Comment by flaneuse** [comment]
Thanks @theosanderson -- that slipped through our quality checks yesterday.  We'll fix it today.

**Comment by flaneuse** [comment]
And please don't hesitate to raise an issue just because you think it might be known; you might have a different perspective on the issue, and in any case, it helps us prioritize what to fix.

**Comment by theosanderson** [comment]
Thanks, I actually happened to be typing a random suggestion which I'll post, just in case:

As an aside (no need to reply) I think a cool feature here could be to set a threshold prevalence below which tiles come up visually as `not detected`, or to reverse the color scale of the heatmap. Essentially a mutation present in 0.1% of lineages might well just be sequencing errors or something, and it's sort of visually confusing to have the very salient white-on-a-dark-background tiles for these. They can kind of overwhelm the purple-on-a-dark-background tiles that are the most interesting.

Just a random thought, no need to reply, thanks as ever
