### ISSUE TITLE
Compare Lineages: reverse color scale and/or filter minimum displayed prevalence

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#376]
Thanks, I actually happened to be typing a random suggestion which I'll post, just in case:

As an aside (no need to reply) I think a cool feature here could be to set a threshold prevalence below which tiles come up visually as `not detected`, or to reverse the color scale of the heatmap. Essentially a mutation present in 0.1% of sequences from a lineage might well just be sequencing errors or something, and it's sort of visually confusing to have the very salient white-on-a-dark-background tiles for these. They can kind of overwhelm the purple-on-a-dark-background tiles that are the most interesting.

![image](https://user-images.githubusercontent.com/19732295/121721570-4f7add00-cadc-11eb-8365-1725994505eb.png)

(Another way of thinking about this is that not detected = 0% )

Just a random thought, no need to reply, thanks as ever

_Originally posted by @theosanderson in https://github.com/outbreak-info/outbreak.info/issues/375#issuecomment-859704690_

**Comment by flaneuse** [comment]
Migrating to a separate issue so I can close #375.

Yeah, the color scale decisions and defaults are very tricky and worth thinking about.  It all depends on what's important and what you want to emphasize.  When I was designing it, I was interested in highlighting the difference between "not found" and "found, but at low prevalence", especially for looking at things like the emergence of E484K in other lineages like B.1.1.7.  Of course, the inherent uncertainty with sequencing complicates this comparison.

I think rather than reversing the color scale, if I change it, I would remove the dark background, since saturated colors are more easily identified as presence rather than absence. 

<img width="1222" alt="Screen Shot 2021-06-11 at 12 29 22 PM" src="https://user-images.githubusercontent.com/8041065/121726832-aff42500-cab0-11eb-96b4-4b47cb3284d9.png">

So, there are three options:
1. Keep the status quo
2. Add an option to switch between light and dark mode, keep dark as default
3. Add an option to switch between light and dark mode, switch to light as default

You also raised the idea of adding a filter to winsorize the data to lump user-set low prevalence with "not detected".  Certainly possible, but slightly more work than switching the background colors.

Will think about this some more; I want to make sure we don't overwhelm the interface and the user with too many options, but these decisions are important to get right.  And I love love love talking about design decisions and thinking if there are better ways to display the data under any circumstances...

**Comment by theosanderson** [comment]
A sort of middle ground is making the colour scale start at a point more distinct from the BG (I realise you don't need me to tell you that):
![image](https://user-images.githubusercontent.com/19732295/121730427-915d5080-cae7-11eb-9d63-d11b30932322.png)

**Comment by flaneuse** [comment]
Yep, that's a possibility too, but it decreases the dynamic range of the color scale.  If/when I implement this, I was going to adjust the diagonal hatch to make it more obviously different.

**Comment by flaneuse** [comment]
@theosanderson this is live now: https://outbreak.info/compare-lineages?dark=false

**Comment by theosanderson** [comment]
Wow - so cool! This will really help me, many thanks!
