### ISSUE TITLE
⚠️ Erroneous collection dates for all the submissions of one French lab

### ISSUE THREAD

**Issue by flodebarre** [outbreak-info/outbreak.info#385]
Hi outbreak.info team, 

FYI, all the "Collection date" information coming from **"Synlab Haut de France"** in the French data on GISAID are erroneous.  

I noticed an issue on GISAID (300+ samples with 1-day delay between collection and submission, submitted on the same day by that lab; proportions of variants off compared to the previous weeks) and I contacted the sequencing lab. They got back to me and explained that the Collection date that they enter is not the date at which the sample was collected, but the date at which the sequencing lab receives samples. They do not have the real collection date information.  
They have multiple other batch submissions with erroneous collection dates. 

Another way to identify the data coming from this "Synlab Haut de France" lab is to look for "HDF-[0-9]" in the virus name field. 

Their submissions are affecting (ruining) the estimations of the proportion of B.1.617.2 / Delta in France, especially for the most recent data (the effect can be seen [here on outbreak.info](https://outbreak.info/situation-reports?pango=B.1.617.2&selected=FRA&loc=USA&loc=USA_US-CA&loc=FRA))

Can you please exclude the data coming from this lab?

**Comment by flodebarre** [comment]
Update: the submitting lab told me that their submissions to GISAID have just been updated with a more vague collection date (YYYY-MM), reflecting the fact that the actual date is unknown.

**Comment by gkarthik** [comment]
@flodebarre Thank you for bringing this to our attention. We will try to exclude these samples from an update soon.

**Comment by flodebarre** [comment]
The new build seems to have correctly excluded these samples ([the B.1.671.2 proportion figure](https://outbreak.info/situation-reports?pango=B.1.617.2&selected=FRA&loc=USA&loc=USA_US-CA&loc=FRA) has changed and makes more sense now), so I am now closing the issue. 

Thanks again for your work on this resource. The website is truly amazing and extremely useful to quickly explore GISAID data. Thanks for making it available to all.

**Comment by flaneuse** [comment]
It's our pleasure @flodebarre! Please let us know if there's any features you'd like to see that would be helpful to your work.
