### ISSUE TITLE
No genomic data for Argentina after 2021-05-19

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#386]
Argentina data seems to cut off after May 15
![Screenshot (368)](https://user-images.githubusercontent.com/75391907/124333867-482e7880-db4a-11eb-9d3a-d8ac571ae661.png)
https://outbreak.info/location-reports?loc=ARG&xmin=2021-01-01&xmax=2021-06-30&selected=B.1.1.7&selected=P.1&selected=C.37

Also, this is a screenshot from today:
![Screenshot (369)](https://user-images.githubusercontent.com/75391907/124333901-609e9300-db4a-11eb-8bf4-837940166b72.png)
But this is a screenshot of the same page from a user on Monday:
![Screenshot (370)](https://user-images.githubusercontent.com/75391907/124333921-6b592800-db4a-11eb-90fd-e5b8c478dbb0.png)
Data may be missing?

**Comment by flaneuse** [comment]
Looks like a data availability issue... Argentina hasn't been producing many sequences.

The reason the colors disappear is based on the time window you choose to group the lineages together into an "other" group. The default is that any lineage which hasn't been detected at a prevalence of > 3% in the past 60 days will be combined into the "other" category, but this can be adjusted.  Will clarify this on the interface
![Screen Shot 2021-08-30 at 1 54 33 PM](https://user-images.githubusercontent.com/8041065/131404192-dc63f848-8871-4050-8aa7-e98154886733.png)
