### ISSUE TITLE
Please add B.1.619 and B.1.620 to "Tracked Lineage" sections

### ISSUE THREAD

**Issue by Mike-Honey** [outbreak-info/outbreak.info#391]
Can you please add B.1.619 and B.1.620 to your mutation report page, e.g. for South Korea?  

They appear as prevalent in the top chart "Lineage Prevalence in ...", but don't appear and can't be selected for any of the "Tracked Lineage" sections. 

https://outbreak.info/location-reports?loc=KOR&selected=S%3AE484K&selected=B.1.1.7&selected=B.1.351&selected=B.1.617.2&selected=P.1&selected=B.1.427&selected=B.1.429&selected=B.1.526&selected=B.1.526.1&selected=B.1.526.2&selected=B.1.617&selected=B.1.617.1&selected=B.1.617.3&selected=P.2

**Comment by flaneuse** [comment]
Thanks for the comment @Mike-Honey. You can actually customize the variants that can be selected by selecting the **Change variants** button next to the prevalence chart or table.  

<img width="1239" alt="Screen Shot 2021-07-12 at 5 59 20 PM" src="https://user-images.githubusercontent.com/8041065/125374521-c9f18380-e34c-11eb-95fd-c385e73ffa68.png">

This will allow you to add any lineage, mutation(s), or combination of lineage with mutations.

<img width="874" alt="Screen Shot 2021-07-12 at 5 59 37 PM" src="https://user-images.githubusercontent.com/8041065/125374566-e2fa3480-e34c-11eb-97b3-2fd769a8ac1b.png">

Here, for instance, is the [location report for South Korea with B.1.619 and B.1.620](https://outbreak.info/location-reports?loc=KOR&pango=B.1.619&pango=B.1.620&selected=B.1.619&selected=B.1.620)

Hope this helps, and let us know if you have other questions or suggestions.
