### ISSUE TITLE
Feature: selecting numerator and denominator for mutation prevalence graph

### ISSUE THREAD

**Issue by theosanderson** [outbreak-info/outbreak.info#405]
[I'd be very surprised if you end up implementing this, as I'm sure it would be a lot of work, but it's something I've found myself wanting for the nth time, so I thought I'd capture it in an issue just in case]

A major use for your (great) prevalence plots, is for people trying to figure out "is this variant/mutation concerning". Lately we've had this with AY.3 in the US. AY.3 has increased a lot in prevalence in some states. But AY.3 is a sublineage of Delta, and we know Delta is fitter than B.1.1.7, so to see AY.3 increasing relative to B.1.1.7 would not be a surprise. But if it is increasing relative to Delta that might be more concerning. There is currently no easy way to disentangle those two possibilities (except downloading the data, which I do!).

If one could somehow select a denominator as well as a numerator for these graphs, that would be super cool.

But as above, I recognise this is a niche request, and satisfied by the data download.

Thanks as ever

**Comment by flaneuse** [comment]
hey @theosanderson -- that's definitely a very interesting question; we've been wondering what the story with AY.3 is as well and relative transmissibility between the Delta+ lineages.  i think this is doable... we'll think some more on it and let you know.
