### ISSUE TITLE
Add AY.3 lineage (= B.1.617.2.3) into default variants of concern

### ISSUE THREAD

**Issue by sacundim** [outbreak-info/outbreak.info#407]
PANGO designated AY.3 as a sub-lineage of B.1.617.2 a few weeks ago. Outbreak.info currently includes AY.1 and AY.2 in its list of variants of concern, but not AY.3. But AY.3 actually has more sequences classified under it than AY.1 and AY.2 combined:

<img width="645" alt="Screen Shot 2021-07-21 at 9 39 17 AM" src="https://user-images.githubusercontent.com/4076056/126526531-fff28ed5-e389-466b-92d2-0e570b82d940.png">

...and since AY.3 was designated as a sub-lineage stemming from some of the big outbreaks in the USA (see references below), it is a big, growing chunk of recent sequences in the USA, at around 15%:

<img width="1219" alt="Screen Shot 2021-07-21 at 9 44 18 AM" src="https://user-images.githubusercontent.com/4076056/126527108-7601c241-29ed-489e-adb5-4f7bf9eba8d9.png">

---
References:

* https://github.com/cov-lineages/pango-designation/issues/121
* https://cov-lineages.org/lineage.html?lineage=AY.3
* https://outbreak.info/location-reports?loc=USA&pango=AY.3&selected=AY.1&selected=AY.2&selected=AY.3&selected=B.1.617.2&xmin=2021-04-30&xmax=2021-07-15

**Comment by sacundim** [comment]
I just noticed that the USA CDC updated its variants info page (apparently on July 20, 2021) to include AY.3 among the lineages aggregated under B.1.617.2/Delta:

<img width="796" alt="Screen Shot 2021-07-21 at 10 41 55 AM" src="https://user-images.githubusercontent.com/4076056/126534871-1a1f1832-903b-46a7-bddc-2b539f10e17a.png">

* https://www.cdc.gov/coronavirus/2019-ncov/variants/variant-info.html

**Comment by gkarthik** [comment]
Thank you for raising this! Should be fixed in https://github.com/outbreak-info/outbreak.info/commit/85f02ef1a90100b832fa689da1cbe9fe1834da66.
