### ISSUE TITLE
Feature requests: relative frequencies and arising mutations

### ISSUE THREAD

**Issue by zach-hensel** [outbreak-info/outbreak.info#408]
Hi -- I'm not an expert in any of this but have been following AY.3 for a while and these two features are things I've been doing manually that would be very nice to automate.

1. Look at X as a fraction of Y sequences in Z where X and Y are sets of mutations and Z is a location. I've used this to track AY.3 for the last few weeks looking at AY.3 (~ORF1a:T3646A + ORF1a:I3731V) as a fraction of the parent lineage (~ORF1a:T3646A; pretty rare outside Delta) in Missouri and Kansas, for example. In the case of AY.3 this would be pretty useful today as people are noticing AY.3 and inferring growth advantages when there is a founder effect.

2. Track growing mutations in a sub-lineage. Essentially the "Lineage Comparison" page except filtering by growth rate of a mutation within a lineage above some thresholds for the growth rate and the error in estimating it. Also it would be useful to be able to define a lineage here and elsewhere by mutations rather pango designation when pango designations have issues.

**Comment by gkarthik** [comment]
Hey @zach-hensel , thank you for raising this issue. This seems related to https://github.com/outbreak-info/outbreak.info/issues/405. We are thinking of a solution to address this.

**Comment by zach-hensel** [comment]
> Hey @zach-hensel , thank you for raising this issue. This seems related to #405. We are thinking of a solution to address this.

Indeed that's basically the same as (1) and I forgot to add the caveat that "this sounds like a lot of work" because it does, with (2) sounding like even more work.

**Comment by flaneuse** [comment]
@zach-hensel @theosanderson: our combined lineage pages now allow you to track the prevalence of a Delta sublineages compared to all lineages:

<img width="1520" alt="Screen Shot 2021-08-30 at 5 14 43 PM" src="https://user-images.githubusercontent.com/8041065/131421722-d575eddf-a1e7-48e9-9fa0-d0c57192dc93.png">

@zach-hensel regarding #2 , we are working on robustly calculating growth rates and incorporating them into the reports. If you haven't seen it, it's possible in both the Variant Reports and the Location Reports to track any mutation or set of mutations, if you don't want to be tied to the classifications of the Pango system. Like: [P681R and L452R](https://outbreak.info/situation-reports?pango&muts=S%3AP681R&muts=S%3AL452R), or as a parameter within the [Location Reports](https://outbreak.info/location-reports?loc=USA&muts=S%3AP681R%20AND%20S%3AL452R&selected=S%3AP681R%20AND%20S%3AL452R&selected=Alpha)
<img width="1268" alt="Screen Shot 2021-08-30 at 6 44 23 PM" src="https://user-images.githubusercontent.com/8041065/131428123-374cd9bc-8429-4ae4-8f90-15f46722f61f.png">


Please let us know if you have other suggestions or notice problems.  Thanks!

**Comment by theosanderson** [comment]
This is super cool and will be incredibly useful! 

I might post a follow-on suggestion when I have time to formulate it, but this is amazing.

**Comment by flaneuse** [comment]
Absolutely! I think there's a lot more that could be done...

**Comment by zach-hensel** [comment]
@flaneuse All of the recent improvements are awesome. The most important one imo that you didn't mention is censoring under sampled data rather than drawing an arrow pointing to it with a warning that was too often ignored!
