### ISSUE TITLE
There's an AY.3.1 now, and figuring out "how much Delta" is getting unwieldy

### ISSUE THREAD

**Issue by sacundim** [outbreak-info/outbreak.info#415]
A couple of weeks ago I reported that an AY.3 lineage had been added (= B.1.617.2.3):

* https://github.com/outbreak-info/outbreak.info/issues/407

And now PANGO added an AY.3.1:

* https://github.com/cov-lineages/pango-designation/issues/147

...and as the title prompted me to check, it actually outnumbers AY.3 and B.1.617.2 combined in Mississippi:

<img width="1227" alt="Screen Shot 2021-08-02 at 5 58 35 PM" src="https://user-images.githubusercontent.com/4076056/127941377-6613863a-bba7-495f-acb6-771ab61bd04d.png">

There's definitely an audience who wants and makes great use of a lineage-based analysis, but I think there's also an audience who would be served well if this website added some combination of:

1. An option to classify and aggregate sequences into Greek letter VOC/VOI that comprise multiple lineages, so that we can visualize e.g. Alpha vs. Delta charts instead of B.1.1.7 vs. B.1.617.2 vs. AY.3 vs. AY.3.1;
2. Some policy on whether new sublineages of VOC/VOIs should, as an overridable default, be grouped with the Greek-letter category;
3. Some automation to detect and include newly added sublineages to the list of VOI/VOC 

Thanks for your great efforts with this invaluable website!

**Comment by corneliusroemer** [comment]
One way to do this, implemented by CovSpectrum, is to have a query type that includes all descendants. B.1.617.2* would include all child lineages.

https://cov-spectrum.ethz.ch/explore/South%20Africa/AllSamples/AllTimes

![Screenshot_20210803-131909~2.jpg](https://user-images.githubusercontent.com/25161793/128006922-f58440dd-6841-4f29-bcd6-c0f13cd0c70a.jpg)

**Comment by flaneuse** [comment]
Thanks @sacundim -- you're completely right that the sublineages of the VOCs are getting quite unwieldy and that combining them makes sense.  We're working on creating sustainable ways to be able to do this for any new lineages (see #416).

In the meantime, we've created a combined [Delta+ report](https://outbreak.info/situation-reports?muts=S%3AT19R&muts=S%3ADEL157%2F158&muts=S%3AL452R&muts=S%3AT478K&muts=S%3AP681R&muts=S%3AD950N) based on the shared mutations between the lineages.

**Comment by FedeGueli** [comment]
New sub-lineages of Delta designated from AY4 to AY.10

https://github.com/cov-lineages/pango-designation/issues/180

Also Gamma new sublineages P.1.9 and 10, 10.1 and 10.2
https://github.com/cov-lineages/pango-designation/issues/179
And Alpha with Q.4
https://github.com/cov-lineages/pango-designation/issues/176

**Comment by flaneuse** [comment]
Thanks @FedeGueli -- we're waiting for those changes to be pushed downstream on GISAID and working on incorporating PangoLearn into our pipelines to streamline this process.

**Comment by rambaut** [comment]
Scorpio (as called by pangolin) will report all these as Delta.

**Comment by flaneuse** [comment]
@sacundim @FedeGueli these changes are now all live at https://outbreak.info/situation-reports and will be updated daily to incorporate any new sublineages.

**Comment by sacundim** [comment]
Saw it earlier. Great work! Thanks!

**Comment by FedeGueli** [comment]
> @sacundim @FedeGueli these changes are now all live at https://outbreak.info/situation-reports and will be updated daily to incorporate any new sublineages.

thank you!!
