### ISSUE TITLE
Situation Reports: add decimal point to y-axis when spacing < 1%

### ISSUE THREAD

**Issue by batson** [outbreak-info/outbreak.info#420]
When y-axis ticks for variant percentages having spacing < 1%, it is difficult to read the graph. In the below examples, values (such as 0 or 1) are repeated many times.

![Screen Shot 2021-08-09 at 1 23 37 PM](https://user-images.githubusercontent.com/1261162/128769476-4ac18ce9-7729-41d3-8545-143772f98505.png)

![Screen Shot 2021-08-09 at 1 21 51 PM](https://user-images.githubusercontent.com/1261162/128769397-08cc9186-182b-4f7d-916b-ff9e307473ad.png)

**Comment by flaneuse** [comment]
thanks @batson, will add this soon.
