### ISSUE TITLE
Add caveat to Delta sublineages about classification changes

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#422]
Suggestion from Twitter: https://twitter.com/chrischirp/status/1428065684995596297
It might be good to add a caveat to AY pages like "Classifications of Delta lineages are in flux. While underlying sequence data remains the same, reports for specific lineages may change."

We could also add a definition of AY lineages to the top paragraph of each of their pages, such as (taken from Laura's help email response) "The AY.4 lineage is a sublineage of the B.1.617.2 lineage and shares many mutations with the other Delta lineages.  As more Delta sequences are found, they are getting reclassified into new but related lineages."

**Comment by flaneuse** [comment]
Will add in the next deployment.
