### ISSUE TITLE
Location reports: unclear that "characteristic mutations" is global not local

### ISSUE THREAD

**Issue by theosanderson** [outbreak-info/outbreak.info#423]
In my opinion there is an implication from the context that `Characteristic S-gene mutations in common lineages over the last 60 days` displays percentages from the country in question rather than globally, despite the helpful `Mutations in at least 75% of global sequences` message.

One possibility is: `Characteristic S-gene mutations globally for lineages common over the last 60 days in this region`

or a change to that `Mutations in at least..` subheading to be more explicit.

I appreciate there's always a trade-off between usability and precision.

**Comment by flaneuse** [comment]
thanks @theosanderson, will fix this in the next deploy.
