### ISSUE TITLE
Truncated text in breakdown of world bank regions is confusing

### ISSUE THREAD

**Issue by gtsueng** [outbreak-info/outbreak.info#427]
When 'exploring a region' (world bank region), clicking on a region will pop-up a breakdown for that region. The location with the highest incidence of whatever will have a longer bar, and its text is truncated (and appears misleading) because of it.
![image](https://user-images.githubusercontent.com/9200138/131549774-61b19b6a-573e-48fc-9969-eabb3f8bf213.png)

**Comment by flaneuse** [comment]
thanks @gtsueng -- i've had to extend the margins so many times in this project to accommodate larger case/death loads :(
