### ISSUE TITLE
Q27* not valid selector, adding .replace("*","star") in relevant lines

### ISSUE THREAD

**Issue by babarlelephant** [outbreak-info/outbreak.info#433]
Hi, the issue is in https://outbreak.info/compare-lineages?pango=B.1.1.7&gene=ORF8 when hovering the Q27* mutation

I compiled the web subdirectory and it seems to work when adding .replace("*","star") in the following lines of https://github.com/outbreak-info/outbreak.info/blob/master/web/src/components/MutationHeatmap.vue

271
370
506
507
519
520
694
707

(a common function to handle all the characters in id and class might be better)

**Comment by flaneuse** [comment]
thanks @babarlelephant, should be fixed now.
