### ISSUE TITLE
MAlaysia is spelled incorrectly

### ISSUE THREAD

**Issue by cpalmquist19** [outbreak-info/outbreak.info#442]
Super minor. In the **Cumulative Prevalence** section of this **Situation Report** (https://outbreak.info/situation-reports?muts=ORF1b%3AP1000L) **Malaysia** is spelled **MAlaysia**.
![image](https://user-images.githubusercontent.com/6631287/133849136-fa8212b2-7c7c-4a0c-a24c-ace4432cf006.png)

**Comment by flaneuse** [comment]
Data was corrected by the submitting lab.
