### ISSUE TITLE
Puerto Rico data disaggregation/glitches

### ISSUE THREAD

**Issue by sacundim** [outbreak-info/outbreak.info#459]
I'm looking at this URL, which I have in a tab from days ago so I hit reload instead of navigating to it through the website UI:

* https://outbreak.info/location-reports?loc=PRI

I click on "Change Location," type Puerto Rico, and I see this:

<img width="990" alt="Screen Shot 2021-10-15 at 4 48 01 PM" src="https://user-images.githubusercontent.com/4076056/137565264-7a1b4c99-0506-4466-b0a6-8196a7ac8f83.png">

I tried to change to some of those locations from that screenshot, and it didn't work.

---
Now on the homepage, I tried selecting some of the locations for "Puerto Rico" after the top one that says 2,998. The one for "Puerto Rico, USA" (with 204 sequences) leads to this:

* https://outbreak.info/location-reports?loc=PRI_PR-PO

<img width="868" alt="Screen Shot 2021-10-15 at 4 55 07 PM" src="https://user-images.githubusercontent.com/4076056/137565447-cd67fc90-0a5a-49df-bb13-95832b28e802.png">

Aguas Buenas is just one smaller municipality in Puerto Rico. Also, the code `PRI_PR-PO` argument to the `loc` URL parameter sounds like that should be Ponce, a different municipality. Likewise when I select the "Puerto Rico, Puerto Rico" with three entries that takes me to `loc=PRI_PR-CG`, in which `CG` should stand for Caguas, but the top of the page looks like this:

<img width="818" alt="Screen Shot 2021-10-15 at 4 58 52 PM" src="https://user-images.githubusercontent.com/4076056/137565566-1f44bbf4-c87b-4bbe-b39f-bcdb89efda0b.png">

Ponce and Caguas, it may be noted, are where two of the universities with viral sequencing programs are located. 

The other `loc` codes I see are:

* `PRI_PR-SJ` (San Juan, but titled "Puerto Rico, USA," 3 sequences)
* `PRI_PR-BY` (Bayamón, titled "Puerto Rico, USA," 1 sequence)
* `PRI_PR-GB` (Guaynabo, titled "Puerto Rico, Puerto Rico," 1 sequence)
* `PRI_PR-HU` (Humacao, titled "Puerto Rico, Puerto Rico," 1 sequence)

**Comment by flaneuse** [comment]
@sacundim we've fixed the location issue.  The new url is: https://outbreak.info/location-reports?loc=USA_US-PRI
