### ISSUE TITLE
Can't see location reports due to missing reportQuery field in Omicron variant

### ISSUE THREAD

**Issue by crossfire** [outbreak-info/outbreak.info#476]
Hello, currently I can't see any location reports, e.g. https://outbreak.info/location-reports?loc=JPN with infinite loading spinner. Also, the browser console shows an error below:
![2021-11-27 07 28 55 outbreak info f71f364388bc](https://user-images.githubusercontent.com/201758/143659039-5166fe77-2d13-487f-8eb3-e9b01fe4c8b5.png)

I checked the error and found missing `reportQuery` field in the definition of `Omicron` variant in [curated_lineages.json](https://github.com/outbreak-info/outbreak.info/blob/4102e309daea57a9d86d07a9796f0e3a05b8ca65/web/src/assets/genomics/curated_lineages.json).
```
~$ jq '.[] | select(.reportQuery == null) | .label' curated_lineages.json
"Omicron"
```
So, looks like it causes the error because of trying to read `reportQuery.loc` although `reportQuery` variable is `undefined`.
https://github.com/outbreak-info/outbreak.info/blob/b3673f04b11e1cea5334e6e2fbdefb8ee5a3b76c/web/src/api/genomics.js#L1446-L1447

My environment:
* OS: Windows 10 Version 21H1 (Build 19043.1348)
* Browser: Vivaldi 4.3.2439.65 (JS engine: V8 9.4.146.24)

**Comment by gkarthik** [comment]
Thank you for raising this! Pushed a fix that should be deployed soon.
