### ISSUE TITLE
US data is not being processed

### ISSUE THREAD

**Issue by aschepler** [outbreak-info/outbreak.info#481]
Many pages on outbreak.info do not correctly show data for states and counties in the United States, or only show it up to Nov. 14, 2021. For example, https://outbreak.info/epidemiology does not list Pennsylvania as selectable at all, and graphs "Ohio State, USA" end at Nov. 14.

The note at the top of README.md for https://github.com/nytimes/covid-19-data might be relevant:

> UPDATE: The county-level data for cases and deaths that includes seven-day averages and per 100,000 counts is now available in year-based files [here](https://github.com/nytimes/covid-19-data/blob/master/rolling-averages). The us-counties.csv file in that directory containing county data since the beginning of the pandemic has been archived and will not be updated.

**Comment by flaneuse** [comment]
thanks @aschepler -- we're in the process of revamping our cases & deaths epi pipeline and hope to have a fix in the next week or two.
