### ISSUE TITLE
All MOI protein structure links go to E484K

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#487]
All Mutation of Interest links to Aquaria under "Protein Structures" at https://outbreak.info/situation-reports#moi are routing to https://aquaria.app/SARS-CoV-2/S/7krq/A?E484K

![Screenshot (584)](https://user-images.githubusercontent.com/75391907/147907306-b2d4cab0-d121-4c58-894d-0bb17e6e5f87.png)

**Comment by flaneuse** [comment]
thanks @EmilyHaag !
