### ISSUE TITLE
Add B.1.640.2 pango lineage [mutations] [enhancement]

### ISSUE THREAD

**Issue by s0menickname** [outbreak-info/outbreak.info#488]
Please add B.1.640.2 variant.
That's a new variant, so-called 'IHU variant' with many mutations including  that emerged in Southern France this fall.
Parent lineage of B.1.640 has been declared as variant under monitoring by WHO. However, there's a big difference between B.1.640.1 and B.1.640.2 — not only in spike (that includes S:E484K) but also a huge amount in other proteins.

**Comment by flaneuse** [comment]
Thanks @s0menickname. This change will be reflected on outbreak.info when GISAID re-runs its Pango lineage assignments.
