### ISSUE TITLE
The "Lineage prevalence" section for the United States is not displayed

### ISSUE THREAD

**Issue by 3dgiordano** [outbreak-info/outbreak.info#513]
When you enter the following link https://outbreak.info/location-reports?loc=USA
The "Lineage prevalence" section is not displayed.

I also see errors in network with code 500 (Internal server error) on the following api.
https://api.outbreak.info/genomics/prevalence-by-location-all-lineages ...

I tried with other countries and it doesn't happen, I think it's only with United States.

**Comment by flaneuse** [comment]
@3dgiordano thanks for bringing this to our attention-- something is definitely screwed up.  We'll fix this soon.

**Comment by flaneuse** [comment]
@3dgiordano -- we've fixed the underlying issue.  Please let us know if you spot any other issues or have suggestions.  Thanks!
