### ISSUE TITLE
Missing county names

### ISSUE THREAD

**Issue by bms44974** [outbreak-info/outbreak.info#515]
County name missing for name in NC and PA (perhaps other states). It appears that, at least in these two states, that the county with the highest number of sequences is missing the name of the county (see attached)
![2022-05-14_13-33-22](https://user-images.githubusercontent.com/33835085/168442702-2e1de664-dcf0-4054-b1d0-f40a4e93c734.jpg)
.

**Comment by bms44974** [comment]
e.g. https://outbreak.info/situation-reports/omicron?loc=USA&loc=USA_US-NC&loc=USA_US-PA&loc=USA_US-CO&loc=USA_US-WV&loc=USA_US-VT&selected=USA_US-PA&overlay=false

**Comment by flaneuse** [comment]
Thanks for raising this issue. These are sequences within the state that have not been assigned a county in GISAID-- the metadata is missing.

**Comment by bms44974** [comment]
![2022-05-14_13-41-23](https://user-images.githubusercontent.com/33835085/168442847-1cf81563-34b5-4d17-9f6c-9b29f7c656fe.jpg)
example from NC. I am sure that the missing name is Wake County

**Comment by bms44974** [comment]
Thanks! Sorry for the inane query. 😊
