### ISSUE TITLE
Unable to view Lineage Comparison on Web

### ISSUE THREAD

**Issue by howard-ryan** [outbreak-info/outbreak.info#516]
Hi, I'm having trouble accessing the Lineage Comparison information via the web app (i.e. https://outbreak.info/compare-lineages ). I've tried a couple different computers/web browsers. The page loads, but no lineage comparison is shown (e.g. no images like I'm accustomed to seeing.) I noticed that at the top of the page, the GISAID sequences were recently updated, but no count is given ("with [ ] sequences from GISAID"). Could GISAID connectivity be the issue? Perhaps I'm doing something dumb. Thanks for your assistance! 

![error](https://user-images.githubusercontent.com/53905362/168864786-db2eac47-6581-45d4-aca0-2a0460688fae.PNG)

**Comment by flaneuse** [comment]
Should be fixed now-- please let us know if you spot other issues.  Thanks!
