### ISSUE TITLE
Compare Lineages visualization limited by browser window width

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#541]
The compare lineages visualizations and caveat text are cut off by the width of the browser window. We could enable horizontal scrolling or resize the visualizations and wrap the text.
![Screenshot (671)](https://user-images.githubusercontent.com/75391907/181622772-ebb52737-bfb3-4757-b412-b498215432ca.png)

**Comment by flaneuse** [comment]
@olekkorob -- don't we have a horizontal scroll?  If not, we should implement it.

Wrapping the text won't really work in this situation.

**Comment by flaneuse** [comment]
@EmilyHaag can you check if this is resolved for you?  it looked good to me.  if so, please feel free to close the issue.

**Comment by EmilyHaag** [comment]
Yes it looks good to me
