### ISSUE TITLE
Compare lineages: slightly confusing UX where "Change Lineages" can appear to do nothing

### ISSUE THREAD

**Issue by theosanderson** [outbreak-info/outbreak.info#543]
I made a recording of this minor issue: https://www.loom.com/share/602d5c5528a24e0aae336528e1206cbb  basically if you scroll down then when you click "Change lineages" on the Compare Lineages page, the panel to change these appears off your screen and it is not obvious that the button has achieved anything. IMO it would be slightly better if in such circumstances the UI scrolled to reveal the new panel. 

This was on Chrome.

Thanks as ever, feel free to close without actioning

**Comment by flaneuse** [comment]
Thanks @theosanderson -- totally agree.  Will fix this now.
