### ISSUE TITLE
Add suggestion to change date window for Location Reports with no recent data

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#578]
Currently, on the San Diego Location Report (http://localhost:8080/location-reports?loc=USA_US-CA_06073&dark=true), the default option for the Lineage prevalence over time only has lineages named "other".

When that happens, add a note to suggest to the user that they change the date window:

<img width="1708" alt="Screenshot 2022-11-10 at 1 29 46 PM" src="https://user-images.githubusercontent.com/8041065/201209899-6243bc53-c5b2-4191-822e-9c06916bb470.png">

**Comment by olekkorob** [comment]
I checked indicated page, but I don't see the issue you described here.
![image](https://user-images.githubusercontent.com/92925885/204051604-1fd6caec-c6df-4ba5-8898-d04f13cd12ac.png)

**Comment by flaneuse** [comment]
Ah, the data has changed since I made this issue.  If you change that window to 10 days, it should lump everything into "other".  When the length of lineages is only 1 (aka everything is other), I would add a notification to suggest to the user that they adjust the "show data from the last X days" input box.

Let me know if this is confusing or you have other questions.

**Comment by flaneuse** [comment]
closed in #595
