### ISSUE TITLE
lineage comparison not working

### ISSUE THREAD

**Issue by Lukas67** [outbreak-info/outbreak.info#584]
When accessing lineage comparison it seems like the webpage has no access to GISAID (shows with [] sequences from GISAID).

What is the problem here? Could it be my network? However tried in another network and everthing works fine.

**Comment by flaneuse** [comment]
Thanks for pointing out this behavior @Lukas67. Our API was momentarily down due to a large number of requests.  It should be back up right now.  Please let us know if you have any other issues with the website.
