### ISSUE TITLE
Remove prepopulated queries for https://outbreak.info/compare-lineages

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#604]
Right now, on the page load, https://outbreak.info/compare-lineages loads the variants of concern to compare, which is a decently heavy query.  

# Goals:
To improve the page load, we want to remove the curated lineages as the default condition if there's no `pango` parameter and force the user to request individual lineages instead. There are also a couple of bugs to fix at the same time.

# Individual tasks:
1. Stop a default `pango` parameter from being set on page load if it's empty
2. Change the expansion panel to "change lineages" be open on page load
3.  Add buttons to add the current CURATED variants as variants
<img width="1000" alt="Screenshot 2022-12-13 at 5 36 40 PM" src="https://user-images.githubusercontent.com/8041065/207483520-c62b212d-f772-4fbf-9a3f-cb79ae96bcf2.png">

⬆️ these tasks have been completed (I think) on the [compare-lineage-no-preload branch](https://github.com/outbreak-info/outbreak.info/tree/compare-lineage-no-preload)

# Additional tasks:
4. Remove the `sub` parameter and the associated "include sublineages" checkbox option
<img width="286" alt="Screenshot 2022-12-13 at 5 39 43 PM" src="https://user-images.githubusercontent.com/8041065/207483945-736e2f8c-d8e8-4ffc-b725-7038a65e45d4.png">
5. Double check that refreshing a route loads the right parameters
6. In box 2 (WHO VOC/VOI sublineages), remove the "clear and add X lineages" button.
7. In boxes 2-5, don't trigger the route change/execution of the form, but just add the results to the selected lineages variable. The user will have to click "create report" to add them.
8. If there's other bugs/issues you see, please suggest changes!

**Comment by olekkorob** [comment]
You mean 1,2,3 tasks are already done?

**Comment by flaneuse** [comment]
Yep, should be!

**Comment by flaneuse** [comment]
closed in #608
