### ISSUE TITLE
improve mobile responsiveness

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#61]
- table headers wrong, etc.

**Comment by EmilyHaag** [comment]
I found a few instances of overlapping headers/labels in the mobile version that don't occur in the desktop version:

**Resources**
The summary plot and last updated date at the top of https://outbreak.info/resources
(Only if zoomed in 125%)
<img src="https://user-images.githubusercontent.com/75391907/187547933-9dec8c50-6c02-4533-a7dc-e8f34a534a10.png" width="200" />
<img src="https://user-images.githubusercontent.com/75391907/187548249-6749e6d6-496c-47da-9f6c-8a985e6a3dfd.png" width="200" />

The button for "Access all data in our API" at the top of https://outbreak.info/sources
<img src="https://user-images.githubusercontent.com/75391907/187548633-aed8b5f1-d406-4524-a497-a2656e41e64d.png" width="200" />

**Situation Reports**
The Cumulative Prevalence title at https://outbreak.info/situation-reports/omicron
<img src="https://user-images.githubusercontent.com/75391907/187548881-8b57f50e-6882-4fa7-9ed6-6efbe311a0a5.png" width="200" />
