### ISSUE TITLE
lineages.yml from pango lineages website not kept up to date as the official definition of pango releases

### ISSUE THREAD

**Issue by 3dgiordano** [outbreak-info/outbreak.info#619]
I understand that you are using the yml file that the cov-lineages people make public on their website.
https://github.com/cov-lineages/lineages-website/blob/master/data/lineages.yml

Just a warning, that file is usually not up to date with the release definitions of pango release or with master from the cov-lineage github.
https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt

I warn you because, for example, since December 22 the yml has not been updated and pango has had a release on December 5 and the site has not yet reflected that.

I'm noticing this because if you guys use that file for important things, you might be misaligned with the official pango definition.

They could ask the pango folks to do the yml update for the website, or they could implement a parser of the pango notes to generate the same file based on each release of pango so as not to rely on the website's metadata.

**Comment by joshuailevy** [comment]
Hi @3dgiordano! While we used to use that file, we noticed the same issue and decided to make our own version using the https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt file that you mention. Any time the lineage_notes.txt file is updated, a corresponding change should be made automatically here: https://github.com/outbreak-info/outbreak.info/blob/master/curated_reports_prep/lineages.yml

**Comment by 3dgiordano** [comment]
Ok, I understand.

You just needed to update the README.md because reference to that file

https://github.com/outbreak-info/outbreak.info/blob/master/README.md

Regards.

**Comment by joshuailevy** [comment]
Ah, good catch. We'll update that link in the readme. Thanks!
