### ISSUE TITLE
LineageComparison Component autocorrecting to the * version 

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#621]
# Steps to recreate
1. On https://outbreak.info/compare-lineages: click "Change Lineages"
2. In Box 3, select "XBB.1.5"
3. This will then add XBB.1.5* [Omicron (XBB.1.5.X)], when it should have added `XBB.1.5`.

# Desired behavior
* In Box 3, selecting "XBB.1.5" would add `XBB.1.5`
* In Box 2, selecting "XBB.1.5* [Omicron (XBB.1.5.X)]" would add `XBB.1.5* [Omicron (XBB.1.5.X)]`

# Why is this happening?
XBB.1.5 represents the Pango lineage XBB.1.5, whereas XBB.1.5* represents XBB.1.5 and all its descendants (lineages which have evolved from XBB.1.5).  Right now, there's not a way to query this information on the API (yet), so we do a front-end lookup to lookup the sublineages associated with a small set of [curated lineages](https://github.com/outbreak-info/outbreak.info/blob/master/web/src/assets/genomics/curated_lineages.json).  The front-end searches in `CURATED_LINEAGES` if there's a match, and then translates the name and query to be a `OR` query of all the sublineages.

This works, but should not be applied when the user asks explicitly for just that lineage.

# For testing
I would use BQ.1 (1 lineage) vs. BQ.1* (should be ~ 80 lineages)

**Comment by leandrocollares** [comment]
The issue was fixed via PR #608.
