### ISSUE TITLE
[bug] Routing for XBB.1.5* from the Lineage Comparison is broken

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#622]
From the [Lineage Comparison page](https://outbreak.info/compare-lineages?pango=XBB.1.5%2a%20%5BOmicron%20%28XBB.1.5.X%29%5D&gene=ORF1a&gene=ORF1b&gene=S&threshold=75&sub=true&dark=false), clicking on `XBB.1.5* [OMICRON (XBB.1.5.X)]` routes to the [SituationReport page](https://outbreak.info/compare-lineages?pango=XBB.1.5%2a%20%5BOmicron%20%28XBB.1.5.X%29%5D&gene=ORF1a&gene=ORF1b&gene=S&threshold=75&sub=true&dark=false) correctly.

However, the logic within the situation report page doesn't correctly look within `CURATED_LINEAGES` to translate XBB.1.5* into XBB.1.5 + sublineages.  I think it's probably just a case sensitivity issue, since [BQ.1](https://outbreak.info/compare-lineages?pango=BQ.1%2a%20%5BOmicron%20%28BQ.1.X%29%5D&gene=ORF1a&gene=ORF1b&gene=S&threshold=75&nthresh=1&sub=false&dark=false) works properly?

**Comment by leandrocollares** [comment]
The issue was fixed via PR https://github.com/outbreak-info/outbreak.info/pull/608.
