### ISSUE TITLE
Routing from the Location page to Situation Reports pages does not work

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#641]
If you click on the following places, you should link to `/situation-reports` pages with various parameters. However, instead it routes to the Situation Report home page:

1. Routing from stream graph
<img width="478" alt="Screenshot 2023-04-03 at 2 59 27 PM" src="https://user-images.githubusercontent.com/8041065/229637083-7c8e6477-6404-4563-b803-4b33de878cae.png">

2. Routing from stacked bar chart
<img width="212" alt="Screenshot 2023-04-03 at 2 59 37 PM" src="https://user-images.githubusercontent.com/8041065/229637091-275fbd51-8989-44dc-a4eb-f674728ee514.png">

3. heatmap (clicking on an axis label or cell)

<img width="1067" alt="Screenshot 2023-04-03 at 2 59 44 PM" src="https://user-images.githubusercontent.com/8041065/229637045-70e21054-5198-42ef-880e-e97bba6a1161.png">

4. lineages over time
<img width="359" alt="Screenshot 2023-04-03 at 2 58 54 PM" src="https://user-images.githubusercontent.com/8041065/229636911-8cfd2f6e-0f7c-45cc-8cc2-1649568ebd28.png">

5. table
<img width="974" alt="Screenshot 2023-04-03 at 2 59 56 PM" src="https://user-images.githubusercontent.com/8041065/229637117-7484b03c-c4a9-44f5-8bcb-3a810fd8cd4f.png">

**Comment by olekkorob** [comment]
Fixed

**Comment by olekkorob** [comment]
As you can see, I have added it already. It doesn't solve a problem. So I implemented in other way.
Please check again.

**Comment by olekkorob** [comment]
Fixed.
