### ISSUE TITLE
Location repot: changing slider on map for "total samples" does not filter the data

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#642]
See behavior on the live site for the desired filtration.
<img width="1070" alt="Screenshot 2023-04-03 at 3 06 32 PM" src="https://user-images.githubusercontent.com/8041065/229637841-3cd65681-3ae6-42aa-ba51-cbfe50f77fa0.png">

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Issue solved!
