### ISSUE TITLE
Lineage comparison page: changing lineages from "already selected" should not trigger API calls

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#644]
On the lineage comparison page, when you add/remove/clear lineages, the API calls should not be triggered until you click "create report".

The behavior is correct if you add a lineage but not if you remove/clear a lineage.

Have the changes from the current `main` branch been incorporated? I know we fixed this before.

**Comment by olekkorob** [comment]
As I checked, we don't trigger API call when we add/remove/clear lineages. Only route is changing.
