### ISSUE TITLE
Lineage comparison page: Lineage addition box 4 doesn't appear to be working properly

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#645]
If I select "lookup S:E484K-containing lineages" at min prevalence 90% in box 4, it says there are 65 lineages which contain this mutation. All 65 lineages should be shown as pills in the "selected lineages" area, but only 4 are.

<img width="1167" alt="Screenshot 2023-04-03 at 3 31 44 PM (2)" src="https://user-images.githubusercontent.com/8041065/229641402-b38ae483-2111-45ee-8a93-9925c4532c60.png">

**Comment by olekkorob** [comment]
I am sorry, I can't reproduce this issue. It's working properly in my side.
