### ISSUE TITLE
Changing the toggles on the epi map histogram leads to weird filtration

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#648]
Adjusting the sliders doesn't filter the data in predictable ways on https://localhost:8080/maps?location=iso3%3AUSA&admin_level=1&variable=dead_per_100k&date=2023-03-08

<img width="1178" alt="Screenshot 2023-04-03 at 4 09 33 PM" src="https://user-images.githubusercontent.com/8041065/229646072-1fbe0362-4074-4e8a-abcb-1fa21d5b997c.png">

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
While filtering seems to be working, the range of values shown by the slider and the subtitle of the chart are different.

<img width="1348" alt="filtering" src="https://user-images.githubusercontent.com/5790932/230219018-b27b3470-dae6-41b3-8867-8b661acbace4.png">

**Comment by olekkorob** [comment]
Fixed
