### ISSUE TITLE
Bug in http://localhost:8080/compare?location=SouthAsia&similarity=confirmed?

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#649]
On http://localhost:8080/compare?location=SouthAsia&similarity=confirmed, the top graph has the two labels switching back and forth 
<img width="864" alt="Screenshot 2023-04-03 at 4 13 15 PM" src="https://user-images.githubusercontent.com/8041065/229646404-85797747-664c-4b33-86db-0264bd23bbe9.png">

after a few seconds:
<img width="181" alt="Screenshot 2023-04-03 at 4 14 10 PM" src="https://user-images.githubusercontent.com/8041065/229646436-b61cd2d7-659c-49b3-8d3d-9790685eda02.png">

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Testing using different places and statistics showed that the labels kept their original positions.
