### ISSUE TITLE
Location reports: y-axes not rendered

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#651]
Common lineages and daily cases charts' y-axes are not rendered in location reports.

![dailyCases](https://user-images.githubusercontent.com/5790932/229899118-a5d297f8-81ba-4e70-b295-3c531f61aad2.png)
![stackedBarChart](https://user-images.githubusercontent.com/5790932/229899126-f19ec20a-fa18-4e09-b47e-7ee2eebb94a3.png)

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Issue solved!
