### ISSUE TITLE
Lineage reports: x-axes not rendered

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#652]
**Prevalence by location** and **Number of samples sequenced** x-axes are not rendered in lineage reports. This issue may be related to #651.

Steps to reproduce behaviour: 

1. Select **Variants** -> **Location tracker**
2. Enter location, e.g., **United Kingdom**
3. Click on **XBB.1.5** in the area chart

![lineageReports](https://user-images.githubusercontent.com/5790932/229912609-99e1d87c-46b2-4124-b388-cf4c27c8ed32.png)

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Issue solved!
