### ISSUE TITLE
Location reports: annotation and hatched area are not rendered

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#653]
Mutation and case prevalence over time chart's annotation and hatched area are not rendered.

![locationReports](https://user-images.githubusercontent.com/5790932/229916274-67083f1f-aa1c-48c1-8e53-bdc9e1cc3ad6.png)

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Issue solved!
