### ISSUE TITLE
Lineage report: slider not filtering data

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#655]
The **minimum number of total samples** slider is not working. 

Please compare https://outbreak.info/situation-reports?xmin=2022-10-05&xmax=2023-04-05&loc=USA&pango=XBB.1.5.15&selected=USA and http://localhost:8080/situation-reports?xmin=2022-10-05&xmax=2023-04-05&loc=USA&pango=XBB.1.5.15&selected=USA

This issue may be related to #642.

  
<img width="1090" alt="slider" src="https://user-images.githubusercontent.com/5790932/230179590-805a38b8-3c8d-4330-94e6-bbb3102d7c31.png">

**Comment by olekkorob** [comment]
Fixed. Check again

**Comment by leandrocollares** [comment]
Issue solved!
