### ISSUE TITLE
Interactive maps: slider behaviour

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#656]
The slider behaviour is erratic and makes it hard for users to select a date.

![sliderBehaviour](https://user-images.githubusercontent.com/5790932/230417380-9bcad22b-b737-4e2a-9e8c-b7f89ce6e2ee.gif)

**Comment by olekkorob** [comment]
Fixed.

**Comment by leandrocollares** [comment]
Issue solved!
