### ISSUE TITLE
Interactive maps: toggle limits not updated when region is changed

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#657]
When the user changes the region, e.g., from **all countries** to **US state**s or from **US states** to **US counties**,  the toggle limits have to be updated to reflect the new x-scale.

<img width="373" alt="toggles" src="https://user-images.githubusercontent.com/5790932/230601294-39a39983-dd09-47d8-8368-f0a52ed25348.png">

**Comment by olekkorob** [comment]
fixed

**Comment by leandrocollares** [comment]
Issue solved!
