### ISSUE TITLE
Interactive maps: toggle limits not updated when stats are changed

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#658]
When the user changes stats, e.g., from **2-week change in cases/day** to **total cases per capita**, the toggle limits have to be updated to reflect the new x-scale.

This issue may be related to #657. 

<img width="372" alt="toggles_2" src="https://user-images.githubusercontent.com/5790932/230606468-76aefab9-5ffb-4c99-8ffb-4933317f34c7.png">

**Comment by olekkorob** [comment]
fixed

**Comment by leandrocollares** [comment]
Unfortunately, the dropdown menu is not working properly and several chart elements are not rendered. Please compare the images below:

desired behaviour

![desiredBehaviour](https://user-images.githubusercontent.com/5790932/230731234-feba9c0c-98d5-4972-b644-de8b5d748ecf.gif)

current behaviour

![currentBehaviour](https://user-images.githubusercontent.com/5790932/230731267-5bae4682-7e92-486d-9d81-24ddeb9a1752.gif)

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Issue solved!
