### ISSUE TITLE
Research library -> Find research: page buttons don't work

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#662]
Page buttons don't allow users to see results past the first page. Please check the live platform for the desired behaviour.

<img width="747" alt="pageButtons" src="https://user-images.githubusercontent.com/5790932/230789866-85015818-31df-4940-9634-9aea87bb2afc.png">

**Comment by olekkorob** [comment]
I don't understand about this issue. Current is same as live platform

**Comment by leandrocollares** [comment]
Issue solved!
