### ISSUE TITLE
Research library -> Find research: clinical trial cards 

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#663]
Clinical trial results are not displayed appropriately.

current look

<img width="1211" alt="currentClinicalTrial" src="https://user-images.githubusercontent.com/5790932/230790927-191b13b3-59fc-4b21-b47f-7f83b0b47292.png">

desired look

<img width="1162" alt="desiredClinicalTrial" src="https://user-images.githubusercontent.com/5790932/230790937-c3ec7a84-ebcc-4f72-a9a6-dbd78baab25a.png">

**Comment by olekkorob** [comment]
Fixed

**Comment by leandrocollares** [comment]
Issue solved!
