### ISSUE TITLE
Research library -> Find research -> Internal links

### ISSUE THREAD

**Issue by leandrocollares** [outbreak-info/outbreak.info#665]
Links that enables internal navigation within any type of results (publication, clinical trial, dataset, etc) are not styled. Please check the live platform for the desired style.

current look

<img width="1014" alt="currentLinks" src="https://user-images.githubusercontent.com/5790932/230792914-1d0a5792-938a-452c-ba8b-777e23548d9c.png">

desired look

<img width="1020" alt="desiredLinks" src="https://user-images.githubusercontent.com/5790932/230792945-100337f8-ac99-4dc6-8c2b-42261b174223.png">

**Comment by olekkorob** [comment]
Fixed
