### ISSUE TITLE
Images rendered with variables are missing in Vue3

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#669]
Images which are rendered dynamically in loops have incorrect sources:

e.g. `:src="`src/assets/team/${person.img}`"` leads to a broken link.

Switching to [`/src/assets`](https://github.com/outbreak-info/outbreak.info/commit/869c7cd9eaedd9c21faaad375876b04d255d4b2c) does not fix the problem.

`@` syntax, which is supported by Vite, does not seem to work within variables.

Images work fine locally but are broken on the prod deploy.

**Comment by flaneuse** [comment]
Components affected:
Resources.vue --> resources/search
ResourceDescription --> resources/{id}
Press.vue --> /press
SituationReports.vue --> situation-reports
About.Vue --> /about
SourceDescription.vue --> /sources

**Comment by leandrocollares** [comment]
Fixed!
