### ISSUE TITLE
Update meta tags for Resources pages

### ISSUE THREAD

**Issue by EmilyHaag** [outbreak-info/outbreak.info#675]
I've created some [meta tag suggestions](https://docs.google.com/spreadsheets/d/1aDBT2Z-JyUbxePqxHNrfuovRw91ql0fR2qNvoAO4M2U/edit?usp=sharing) to improve SEO of the Research Library.

I don't see a need to change the meta image and I believe we can use the same tags for title as og:title, twitter title, etc.

**Comment by flaneuse** [comment]
@leandrocollares the [Vue-Meta](https://vue-meta.nuxtjs.org/) package is already installed to add this in.

**Comment by flaneuse** [comment]
Also: in the Vue3 migration code, I just noticed that the place where this was used has been lost: https://github.com/outbreak-info/outbreak.info/blob/fe9bd5bca5b6b3177af12a6e1b5ce432257d6f44/web/src/views/ResourcePage.vue#L320

This call to `metaInfo` inserted `<meta>` tags which allowed search engine crawlers like [Google Dataset Search](https://datasetsearch.research.google.com/) to pick them up.  We should also add these meta tags back in eventually.

**Comment by flaneuse** [comment]
Also, you can test the embedded metadata via Google tools: https://developers.google.com/search/docs/appearance/structured-data
