### ISSUE TITLE
System requirements and test setup

### ISSUE THREAD

**Issue by joelkraehemann** [outbreak-info/outbreak.info#78]
Hi,
I need some guidance howto setup outbreak.info locally ...
What are the system requirements?

* needed CPU power
* amount of RAM
* preferred Operating System and version

Further do you provide some test data? I would love to write automated tests, what are your preferences?

**Comment by gkarthik** [comment]
Hey, instructions to get Vue running locally are [here](https://github.com/SuLab/outbreak.info/blob/master/web/README.md). The app runs in a browser and is not particularly heavy so any standard laptop should do the trick. 

We do not have tests for the Vue app set up yet but Vue has [unit testing](https://vuejs.org/v2/guide/unit-testing.html) built in that can be leveraged. @flaneuse should have more details on test data and exactly what components to test.

**Comment by flaneuse** [comment]
For a first pass, it'd be useful to create tests to double check that the aggregated numbers in the [Case Summary Component](https://github.com/SuLab/outbreak.info/blob/master/web/src/api/epi-basics.js) and the [table](https://github.com/SuLab/outbreak.info/blob/master/web/src/components/EpiTable.vue) agree with the [API](https://api.outbreak.info/v1/query?q=admin_level:%22-1%22&sort=date).  Let us know if you run into any issues or notice anything that can be improved, and thanks for looking into testing!
